server:
  servlet:
    context-path: /rabbit/pixelwave/api/color
  port: "8083"
management:
  health:
  endpoint:
    health:
      enabled: true
      show-details: always

spring:
  rabbitmq:
    username: rabbitmq
    password: rabbitmq
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        colorFilter-function-in-0:
          destination: compression.event.compressed-image
        colorFilter-function-in-0:
          destination: color.event.color-filter-image
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
