spring:
  flyway:
    enabled: "true"
    validate-on-migrate: "true"
    locations: classpath:db/migration/prod,classpath:db/migration/dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: "true"
  application:
    name: storage-service
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5440/postgres
image:
  storage:
    directory: uploads/
server:
  port: ${PORT:8080}
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
