---
spring:
  rabbitmq:
    username: rabbitmq
    password: rabbitmq
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        imageCreatedSupplier-out-0:
          destination: storage.event.image-created
        saveProcessedImage-in-0:
          destination: format.event.format-image
  flyway:
    enabled: "true"
    validate-on-migrate: "true"
    locations: classpath:db/migration/prod,classpath:db/migration/dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: "true"
  datasource:
    password: "123"
    username: postgres
    url: jdbc:postgresql://localhost:5441/postgres
image:
  storage:
    directory: minhaPropriedade: ${STORAGE_PATH:uploads/}

server:
  port: "8080"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
