spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
    global-filters:
      - name: Retry
        args:
          retries: 3
          statuses: BAD_GATEWAY
          methods: GET,POST
          backoff:
            firstBackoff: 10ms
            maxBackoff: 50ms
            factor: 2
            basedOnPreviousValue: false
      - name: RequestRateLimiter
        args:
          redis-rate-limiter:
            replenishRate: 400
            burstCapacity: 450
            requestedTokens: 1
  data:
    redis:
      connect-timeout: 2s
      host: localhost
      port: 6379
      timeout: 1s

server:
  port: '8070'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
