server:
  servlet:
    context-path: /dev/pixelwave/api/compression
  port: "8081"
management:
  health:
  endpoint:
    health:
      enabled: true
      show-details: always

spring:
  rabbitmq:
    username: rabbitmq
    password: rabbitmq
    host: localhost
    port: 5672
  cloud:
    stream:
      bindings:
        compressImage-in-0:
          destination: storage.event.image-created
        compressImage-out-0:
          destination: compression.event.compressed-image
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
